apiVersion: apps/v1
kind: Deployment
metadata:
  name: angapp1
spec:
  selector:
    matchLabels:
      app: angapp1
  replicas: 1
  template:
    metadata:
      labels:
        app: angapp1
    spec:
      containers:
        - name: angapp1-app
          image: ang-app
          imagePullPolicy: Never
          ports:
            - containerPort: 80
