apiVersion: apps/v1
kind: Deployment
metadata:
  name: angapp3723
spec:
  selector:
    matchLabels:
      app: angapp3723
  replicas: 1
  template:
    metadata:
      labels:
        app: angapp3723
    spec:
      containers:
        - name: angapp3723-app
          image: docker.io/library/angapp3723_3:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80